# Generated by Django 4.2.6 on 2023-10-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
