# Generated by Django 4.2.6 on 2023-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_choice_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
